/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';

import '@ionic/core';
import 'ionicons';


export namespace Components {

  interface AppHome {}
  interface AppHomeAttributes extends StencilHTMLAttributes {}

  interface AppRoot {}
  interface AppRootAttributes extends StencilHTMLAttributes {}

  interface FirebaseFirestore {}
  interface FirebaseFirestoreAttributes extends StencilHTMLAttributes {}

  interface FirebaseStorage {}
  interface FirebaseStorageAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'AppHome': Components.AppHome;
    'AppRoot': Components.AppRoot;
    'FirebaseFirestore': Components.FirebaseFirestore;
    'FirebaseStorage': Components.FirebaseStorage;
  }

  interface StencilIntrinsicElements {
    'app-home': Components.AppHomeAttributes;
    'app-root': Components.AppRootAttributes;
    'firebase-firestore': Components.FirebaseFirestoreAttributes;
    'firebase-storage': Components.FirebaseStorageAttributes;
  }


  interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {}
  var HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new (): HTMLAppHomeElement;
  };

  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLFirebaseFirestoreElement extends Components.FirebaseFirestore, HTMLStencilElement {}
  var HTMLFirebaseFirestoreElement: {
    prototype: HTMLFirebaseFirestoreElement;
    new (): HTMLFirebaseFirestoreElement;
  };

  interface HTMLFirebaseStorageElement extends Components.FirebaseStorage, HTMLStencilElement {}
  var HTMLFirebaseStorageElement: {
    prototype: HTMLFirebaseStorageElement;
    new (): HTMLFirebaseStorageElement;
  };

  interface HTMLElementTagNameMap {
    'app-home': HTMLAppHomeElement
    'app-root': HTMLAppRootElement
    'firebase-firestore': HTMLFirebaseFirestoreElement
    'firebase-storage': HTMLFirebaseStorageElement
  }

  interface ElementTagNameMap {
    'app-home': HTMLAppHomeElement;
    'app-root': HTMLAppRootElement;
    'firebase-firestore': HTMLFirebaseFirestoreElement;
    'firebase-storage': HTMLFirebaseStorageElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
